[package]
name = "svg3-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
svg3-dom.workspace = true
wgpu.workspace = true
pollster.workspace = true
bytemuck = { workspace = true, features = ["derive"] }
glam.workspace = true
thiserror.workspace = true
log.workspace = true

[dev-dependencies]
criterion.workspace = true
png.workspace = true

[[bench]]
name = "tessellate"
harness = false
